SMRG\GeoserverBundle\Entity\Event:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        latitude:
            type: float
            length: 10
        longitude:
            type: float
            length: 10
        description:
            type: text
    manyToOne:
        track:
            targetEntity: Track
            inversedBy: events
            joinColumn:
                name: track_id
                referencedColumnName: id
    manyToOne:
        eventcategory:
            targetEntity: EventCategory
            inversedBy: events
            joinColumn:
                name: eventcategory_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
