SMRG\GeoserverBundle\Entity\Event:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        latitude:
            type: float
            length: 10
        longitude:
            type: float
            length: 10
        description:
            type: text
            nullable: true

    manyToOne:
        category:
            targetEntity: SMRG\GeoserverBundle\Entity\EventCategory
            inversedBy: events
            joinColumn:
                name: category_id
                referencedColumnName: id
        tracks:
           targetEntity: SMRG\GeoserverBundle\Entity\Track
           inversedBy: events
           joinColumn:
               name: track_id
               referencedColumnName: id


    lifecycleCallbacks: {  }
