SMRG\GeoserverBundle\Entity\Track:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        rating:
            type: integer
            nullable: true
        gpxfile:
            type: string
            length: 100
        attributes:
            type: json_array
            nullable: true
    manyToOne:
        project:
            targetEntity: Project
            inversedBy: tracks
            joinColumn:
                name: project_id
                referencedColumnName: id
    oneToMany:
        events:
            targetEntity: SMRG\GeoserverBundle\Entity\Event
            mappedBy: tracks
            inversedBy: events
        pictures:
            targetEntity: SMRG\GeoserverBundle\Entity\TrackPicture
            mappedBy: track
            inversedBy: pictures
